---
- hosts: tag_Name_Terraform
  tasks:    
  - name: add webupd8 ppa
    become: yes
    apt_repository: repo='ppa:openjdk-r/ppa'

  - name: update
    shell: apt-get update
    sudo: yes

  - name: install java8
    shell: apt-get install -y openjdk-8-jdk
    sudo: yes
